import BlogEnv from "./BlogEnv.js";
import BlogApi from "./BlogApi.js";
import BlogFace from "./BlogFace.js";
import BlogEncryConst from "./BlogEncryConst.js";
window._config = window._config || {};
let BlogContext={};
BlogContext = Object.assign(BlogContext, BlogEnv);
BlogContext = Object.assign(BlogContext, BlogFace);
BlogContext = Object.assign(BlogContext, BlogEncryConst);
BlogContext = Object.assign(BlogContext, BlogApi);
BlogContext = Object.assign(BlogContext, window._config);
export default BlogContext;